#!/bin/bash

if ! command -v nvm &> /dev/null
then
  curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
  source ~/.bashrc

  DEFAULT_VERSION=12.18.3
  nvm install $DEFAULT_VERSION
  nvm alias default $DEFAULT_VERSION
fi