#!/bin/bash

#teams
if ! command -v teams &> /dev/null
then
  echo "$(tput setaf 7)$(tput setab 2)Installing teams$(tput sgr 0)"
  curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main" > /etc/apt/sources.list.d/teams.list'
  sudo apt update
  sudo apt install -y teams
fi

#chrome
if ! command -v google-chrome &> /dev/null
then
  echo "$(tput setaf 7)$(tput setab 2)Installing chrome$(tput sgr 0)"
  CHROME_FILE=google-chrome-stable_current_amd64.deb
  wget "https://dl.google.com/linux/direct/$CHROME_FILE"
  sudo dpkg -i $CHROME_FILE
  rm -rf $CHROME_FILE
fi

# openvpn
echo "$(tput setaf 7)$(tput setab 2)Seeting up vpn$(tput sgr 0)"
if ! command -v openvpn &> /dev/null
then
  sudo apt install -y tzdata openvpn
fi
[ -f /etc/openvpn/client/client.conf ] || sudo cp src/bash/config/vpn/client.conf /etc/openvpn/client/client.conf
[ -f /usr/local/etc/openvpn/login.conf ] || sudo cp src/bash/config/vpn/login.conf /usr/local/etc/openvpn/login.conf
sudo systemctl enable openvpn-client@client.service
