#!/bin/bash

if ! command -v pyenv &> /dev/null
then
  echo "$(tput setaf 7)$(tput setab 2)Seeting up PyEnv$(tput sgr 0)"

  curl https://pyenv.run | bash
  # eval "$(pyenv init --path)"
  # eval "$(pyenv init -)"
  # eval "$(pyenv virtualenv-init -)"
  exec $SHELL

  DEFAULT_VERSION=3.8.8
  pyenv install $DEFAULT_VERSION
  pyenv global $DEFAULT_VERSION

  pyenv virtualenv $DEFAULT_VERSION localdev
fi
