#!/bin/bash

echo "$(tput setaf 7)$(tput setab 2)Start setting up environment$(tput sgr 0)"

sudo apt-get update
sudo apt install -y curl wget git snapd

./git
./nvm
./docker
./dev-tools
./office-tools

echo "Remember to update the credential /usr/local/etc/openvpn/login.conf"
