#!/bin/bash

eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

cd ~/projects/localdev/
git checkout master && git pull newscred master

pyenv activate localdev
nc-docker configure

(
  for repo in cmp-client cmp-server sso assets marketing-work-request permissions notification-service; do
    echo "Pulling $repo"
    nc-docker pull $repo
  done
)
